# Generated by Django 5.1 on 2024-08-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
