# Generated by Django 5.1 on 2024-08-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_alter_travel_end_date_alter_travel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='main_photo',
            field=models.CharField(null=True),
        ),
    ]
