# Generated by Django 5.1 on 2024-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_alter_travel_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='main_photo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
