# Generated by Django 5.1 on 2024-08-14 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_alter_travel_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='medias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='step.media'),
        ),
    ]
