# Generated by Django 5.1 on 2024-08-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0005_alter_step_medias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='descriptions',
            field=models.CharField(blank=True, null=True),
        ),
    ]
