# Generated by Django 5.1 on 2024-08-14 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0007_remove_media_path_media_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='medias',
        ),
        migrations.AddField(
            model_name='media',
            name='step',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='step.step'),
            preserve_default=False,
        ),
    ]
