# Generated by Django 5.1 on 2024-08-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0009_rename_name_media_legend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(upload_to='static', verbose_name='File'),
        ),
    ]
