# Generated by Django 5.1 on 2024-08-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0011_step_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='main_photo',
            field=models.FileField(upload_to='static', verbose_name='File'),
            preserve_default=False,
        ),
    ]
