# Generated by Django 5.1 on 2024-08-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0013_alter_travel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.travel'),
            preserve_default=False,
        ),
    ]
