# Generated by Django 5.1 on 2024-08-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0014_step_travel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='step',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='state',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='step.travel'),
        ),
    ]
