# Generated by Django 5.1 on 2024-08-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0015_alter_step_options_step_country_step_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='legend',
            field=models.CharField(blank=True, null=True),
        ),
    ]
