# Generated by Django 5.1 on 2024-08-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0016_alter_media_legend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='step.step')),
            ],
        ),
    ]
