# Generated by Django 5.1 on 2025-02-08 13:33

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0018_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='positional_step',
            field=models.BooleanField(default=False),
        )
    ]
