# Generated by Django 5.1 on 2025-02-08 14:18

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0019_step_positional_step_alter_media_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(null=True),
        )
    ]
