# Generated by Django 5.1 on 2025-02-12 08:26

import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0020_alter_media_media_file_alter_step_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        )
    ]
