# Generated by Django 5.1 on 2025-10-17 07:06

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0021_travel_owners_alter_media_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[1500, 1200], upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='step',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='positional_step',
            field=models.BooleanField(default=False, verbose_name='Positional step'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='main_photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[1500, 1200], upload_to='', verbose_name='File'),
        ),
    ]
