# Generated by Django 5.1 on 2025-10-17 02:15

import step.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0022_alter_media_media_file_alter_step_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='date',
            field=step.models.DateTimeWithoutTZField(),
        ),
    ]
