# Generated by Django 5.2.8 on 2025-12-22 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0023_alter_step_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="BookLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html", models.TextField(blank=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_layout",
                        to="step.step",
                    ),
                ),
            ],
        ),
    ]
