# Generated by Django 5.1 on 2026-06-08 17:21

import django.core.validators
import django_resized.forms
import step.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0023_alter_step_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"ordering": ["id"]},
        ),
        # Rename rather than drop+create so existing image data is preserved.
        migrations.RenameField(
            model_name="media",
            old_name="media_file",
            new_name="image_file",
        ),
        migrations.AlterField(
            model_name="media",
            name="image_file",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=85,
                scale=None,
                size=[1500, 1200],
                upload_to="",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    ),
                    step.models.validate_video_size,
                ],
                verbose_name="Video",
            ),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("image_file", ""),
                        ("image_file__isnull", True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("video_file", ""),
                        ("video_file__isnull", True),
                        _connector="OR",
                    ),
                    _connector="XOR",
                ),
                name="media_exactly_one_file",
            ),
        ),
    ]
