# Generated by Django 5.2.8 on 2026-06-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0024_add_video"),
        ("step", "0024_travel_uuid_travel_is_public"),
    ]

    operations = []
