# Generated by Django 5.2.8 on 2025-12-22 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0024_alter_media_options_booklayout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booklayout",
            name="step",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_layout",
                to="step.step",
            ),
        ),
    ]
