# Generated by Django 5.1 on 2026-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0025_merge_20260609_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publier ?'),
        ),
    ]
