# Generated by Django 5.2.8 on 2025-12-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0025_alter_booklayout_step"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookLayout",
        ),
    ]
