# Generated by Django 5.1 on 2026-06-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0026_step_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='_from',
            field=models.CharField(null=True),
        ),
    ]
