# Generated by Django 5.2.8 on 2025-12-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0026_delete_booklayout"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html", models.TextField(blank=True)),
                ("primary_color", models.CharField(default="#e28b28")),
                ("travel_zoom_level", models.IntegerField(default=6)),
                ("step_zoom_level", models.IntegerField(default=7)),
                (
                    "travel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_layout",
                        to="step.travel",
                    ),
                ),
            ],
        ),
    ]
