# Generated by Django 5.2.8 on 2025-12-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0027_booklayout"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepBookLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html", models.TextField(blank=True)),
                (
                    "step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_layout",
                        to="step.step",
                    ),
                ),
            ],
        ),
    ]
